version: '3.8'

services:
  app:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./fe:/app
    networks:
      - app-network
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: on-failure

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge
